### ISSUE TITLE
Set up continuous integration Github actions

### ISSUE THREAD

**Issue by svmhdvn** [shracha10/coding-challenges#1]
Might be cool to set up automated testing so that Github can verify that all your solutions work. If you ever add new solutions, or modify old ones, GH will fire an action and output a PASS/FAIL result.

**Comment by shraacha** [comment]
Oh I didn't know that was a thing. I'll definitely look into that!

**Comment by hydrobeam** [comment]
What's the progress on this so far?

**Comment by hydrobeam** [comment]
I'm not too familiar with how Java is built, but rust should be fairly straightforward to set up in theory. At a cursory glance, the issue seems to be that your `main.rs` file in `aoc-2022` can only run one day's solution at a time. 

To get around this you could parse some command line arguments that control which day runs. Or every day could be run simultaneously and you check for an error code.

Unfortunately, I don't think this is a problem that can be solved without some architecture redesign.

**Comment by shraacha** [comment]
Cargo is able to build and run tests for rust projects. 

I have added some tests for each of my completed days in `main.rs` (using the example input, and the main problem inputs) and integrated this into a GitHub workflow. Those browsing my 2022 solutions directory can now see whether all of my completed solutions are working.
